ajout du html et css spectacles
TriciaFolke/delazur pull request #1
Opened 2022-10-24 17:47 UTC by catdub40

ajout des fichiers spectacles.htm; et spectacles.css

2022-10-24 17:49 UTC, TriciaFolke commented
Parfait pour moi

2022-10-24 17:51 UTC, TriciaFolke approved these changes
J'approuve !

2022-10-24 18:26 UTC, imonlyashes requested changes
Il faudrait ajouter **type="button"** sur les boutons  :)

2022-10-24 18:59 UTC, catdub40 commented
La modification du type button est fait!

2022-10-24 19:27 UTC, imonlyashes approved these changes
Super merci pour le type! :)

2022-10-24 22:27 UTC, SysyRoy commented
Suite à ma première demande, finalement c'est ok pour le survol des médias sociaux. C'est dû au fait que je passais trop rapidement sur les icônes. Ils n'avaient pas le temps de réagir.

2022-10-25 15:27 UTC, SysyRoy approved these changes

2022-10-25 15:52 UTC, cynophilo approved these changes

2022-10-25 19:15 UTC, merged