added modal and breakpoint
TriciaFolke/delazur pull request #3
Opened 2022-10-25 23:23 UTC by imonlyashes

- Ajout de la modale dans le html et le css
- Ajout de JavaScript pour la modale
- Ajout du breakpoint à 1200 px pour affichage de la grid
- Ajout d'une flexbox pour avant le breakpoint
- Ajustement du bouton d'abonnement à l'infolettre
- Retrait de la dernière rangée de la grid
- Ajout de l'état actif sur le lien spectacles de la navigation
- Modification de la taille du h1 (il était trop petit par rapport à la taille dans la maquette vs la taille de la navigation)
- Ajout de letter spacing sur le h1
- Ajout du type="button" sur les boutons des spectacles
- Ajout d'état de focus sur les boutons

2022-10-26 03:11 UTC, catdub40 commented
C'est parfait!

2022-10-26 03:13 UTC, catdub40 approved these changes

2022-10-26 12:06 UTC, SysyRoy approved these changes

2022-10-26 13:08 UTC, TriciaFolke commented
Oh je pensais que la modale rentrait dans la dernière rangée. Merci pour les ajustements. Belle job !

2022-10-26 13:45 UTC, TriciaFolke approved these changes

2022-10-26 15:26 UTC, imonlyashes commented
> Oh je pensais que la modale rentrait dans la dernière rangée. Merci pour les ajustements. Belle job !

Je pense bien que tu as raison! J'ai mal vu l'alignement, je pensais que c'était plus large que la grid. Je vais ajuster ça!

**En ajustant je me suis aussi rendue compte qu'il y a deux spectacles pour lesquels la place dans la grid était pas bonne. Le carré 150 et Amphithéâtre Cogeco devaient être décalés de un vers la droite (carré 150 était aligné avec Club Soda alors qu'il devait l'être avec Café Campus et Amphithéâte était aligné avec le Centre culturel et ne devait pas l'être). Donc j'ai ajusté ça aussi au passage. Là tout devrait être bon.

2022-10-28 13:30 UTC, cynophilo commented
Ajouter un commentaire dans le html au sujet du h1 : Comme le h1 est déjà dans le header, on a mis un h2 dans le main

2022-10-28 13:32 UTC, cynophilo requested changes
Voir mon commentaire plus haut...

2022-10-28 13:58 UTC, imonlyashes commented
La modification est faite au niveau du h1 etc. pour qu'il n'y ait pas un doublons de h1 dans la page. Je merge le tout comme convenu en vocal Teams! :)

2022-10-28 13:59 UTC, merged