Add contact css
TriciaFolke/delazur pull request #5
Opened 2022-11-09 01:30 UTC by catdub40

Veuillez vérifier si tout est correct!

2022-11-09 13:02 UTC, imonlyashes requested changes
**HTML**
- Il faut que le name des boutons radio soit le même pour tous pour qu'on puisse choisir une seule option, ce qui n'est pas le cas en ce moment.

**CSS GÉNÉRAL**
- Il faudrait changer le media querie. Il faudrait placer "min-width: 1200px" plutôt (J'ai appris cette semaine qu'on doit le plus possible utiliser le min-width avec les media querie donc ce sera la meilleure façon d'ajuster le tout. :) ) et il faudrait inverser les grid et le flex dans le css (donc placer les grid dans le media querie et placer le flex en-dehors). Parce qu'on a un soucis d'affichage au niveau du prénom et de la date actuellement dans le premier bloc ainsi qu'au niveau du troisième bloc par rapport à la marge de droite (images, mois, site à découvrir, date et heure du show) et aussi pour le mot de passe pour lequel la ligne ne fait pas toute la largeur.

- Il manque l'état de hover et focus sur les boutons. Aussi, le bouton "envoyer" devrait être "soumettre" et les deux boutons ne sont pas du même format alors qu'ils devraient l'être.

**CSS -1200px (donc à ajuster en dehors du media querie)**
- Il faut diminuer la marge de gauche des input. Dans la maquette ils sont vraiment plus près du bord gauche que du bord droit.

- Il faut ajouter du padding à droite dans le input des provinces, le nom n'est pas collé à gauche comme ça dans la maquette.

- Le label du pays est collé sur les provinces, il faut ajuster ça.

- Il faut réduire l'espace être le range et son label. Il est moins grand dans la maquette.

- Les checkbox n'affichent pas correctement. Il faudrait les placer entre div pour ne pas que la case soit séparée de son label et il faudrait aussi ajuster l'espacement entre chacune parce qu'il est trop grand.

- Il faut ajuster l'espacement des boutons radio et aussi l'espacement dans le fieldset. Dans la maquette l'espacement est énormément plus petit.

- Les boutons ne sont pas centrés correctement en petit format d'écran.

**CSS +1200px (donc à ajuster dans le media querie)**
- Il y a un ajustement à faire au niveau des marges des input dans la première partie. Quand on regarde bien la maquette, on peut constater que l'espacement de droite est beaucoup plus grand que celui de gauche. Il est aussi inégale d'une ligne à l'autre (la ligne de nom de famille se rend plus loin que la ligne d'adresse courriel par exemple).

- L'espacement est trop grand dans le bas de chacun des fieldset. Il est beaucoup plus petit dans la maquette. Il devrait cependant être plus grand dans le haut des fieldset.

- Pour couleur préférée et images préférées il faut réduire l'espacement en hauteur qui est moins grand sur la maquette.

- La marge de gauche pour tous les éléments du troisième bloc devrait être plus grande. La marge de gauche également pour tous les éléments, mais aussi entre les éléments.

- Il faudra ajouter un display: inline aux div prédécemment ajoutées sur les checkbox pour qu'elles affichent correctement et ajuster l'espacement.

---------------------------------------------------------
Désolé pour toutes les petites notes, mais c'est ce que j'ai vu en comparant avec la maquette.

2022-11-09 17:32 UTC, SysyRoy approved these changes

2022-11-09 18:12 UTC, TriciaFolke approved these changes

2022-11-09 19:19 UTC, cynophilo commented
ok Catherine, j'suis pas sûr de tout comprendre... merci d'avoir pris le lead de faire les correctifs :)

2022-11-09 21:41 UTC, imonlyashes commented
J'ai fait toutes les modifications mentionnées ci-haut. J'ai aussi ajouté une div sur les boutons pour les centrer correctement dans les deux versions. J'ai enlevé le flex sur le mot de passe parce que ça ne servait à rien de le garder. J'ai aussi modifié les sélecteurs "input" "label" "legend" dans le css pour "form input" "form label" et "form legend" parce que j'ai aussi dû utiliser des input avec la modale comme ça on va s'éviter un bug. :)

Normalement tout est ok par rapport à la maquette.

2022-11-09 21:42 UTC, imonlyashes approved these changes

2022-11-10 13:28 UTC, cynophilo approved these changes

2022-11-10 14:07 UTC, merged