Accueil
TriciaFolke/delazur pull request #6
Opened 2022-11-09 20:05 UTC by SysyRoy

Juste véfifier les tableaux disproportionnés

2022-11-09 21:23 UTC, TriciaFolke reviewed
Salut Sylvie, j'ai regardé ton code pour essayer de comprendre les proportions des tableaux et ça me semble beau de mon bord quand je l'inspecte dans le navigateur chrome. Peut-être que je ne comprends pas ta demande de vérification...

2022-11-10 12:55 UTC, imonlyashes requested changes
Il faudrait ajuster deux petites choses :)

- Le texte du p ne semble pas être en bold dans la maquette alors il faudrait enlever ça (ligne 23 dans le css).
- On a aussi oublié de modifier le nom du fichier pour index.html pour ne pas avoir de soucis avec la navigation. 

C'est pas mal tout. Je ne trouve pas la solution pour les tableaux non plus. :(

2022-11-10 13:28 UTC, cynophilo approved these changes

2022-11-10 16:32 UTC, catdub40 approved these changes

2022-11-10 16:36 UTC, imonlyashes approved these changes

2022-11-10 16:41 UTC, TriciaFolke commented
J'ai apporté quelques modifications au css et au html. Et j'ai apporté des modifications à la demande de 
imonlyashes

2022-11-10 16:41 UTC, TriciaFolke approved these changes

2022-11-10 17:04 UTC, merged